/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackBookingIdRouteImport } from './routes/track.$bookingId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InvoiceBookingIdRouteImport } from './routes/invoice.$bookingId'
import { Route as BookServiceIdRouteImport } from './routes/book.$serviceId'
import { Route as AuthSignupExpertRouteImport } from './routes/auth.signup-expert'
import { Route as AuthSignupCustomerRouteImport } from './routes/auth.signup-customer'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/expert/',
  path: '/expert/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackBookingIdRoute = TrackBookingIdRouteImport.update({
  id: '/track/$bookingId',
  path: '/track/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceBookingIdRoute = InvoiceBookingIdRouteImport.update({
  id: '/invoice/$bookingId',
  path: '/invoice/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceIdRoute = BookServiceIdRouteImport.update({
  id: '/book/$serviceId',
  path: '/book/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupExpertRoute = AuthSignupExpertRouteImport.update({
  id: '/auth/signup-expert',
  path: '/auth/signup-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupCustomerRoute = AuthSignupCustomerRouteImport.update({
  id: '/auth/signup-customer',
  path: '/auth/signup-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-customer': typeof AuthSignupCustomerRoute
  '/auth/signup-expert': typeof AuthSignupExpertRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/p/$slug': typeof PSlugRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/expert/': typeof ExpertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-customer': typeof AuthSignupCustomerRoute
  '/auth/signup-expert': typeof AuthSignupExpertRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/p/$slug': typeof PSlugRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/admin': typeof AdminIndexRoute
  '/expert': typeof ExpertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup-customer': typeof AuthSignupCustomerRoute
  '/auth/signup-expert': typeof AuthSignupExpertRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/p/$slug': typeof PSlugRoute
  '/track/$bookingId': typeof TrackBookingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/expert/': typeof ExpertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/auth/login'
    | '/auth/signup-customer'
    | '/auth/signup-expert'
    | '/book/$serviceId'
    | '/invoice/$bookingId'
    | '/p/$slug'
    | '/track/$bookingId'
    | '/admin/'
    | '/expert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/auth/login'
    | '/auth/signup-customer'
    | '/auth/signup-expert'
    | '/book/$serviceId'
    | '/invoice/$bookingId'
    | '/p/$slug'
    | '/track/$bookingId'
    | '/admin'
    | '/expert'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/wallet'
    | '/auth/login'
    | '/auth/signup-customer'
    | '/auth/signup-expert'
    | '/book/$serviceId'
    | '/invoice/$bookingId'
    | '/p/$slug'
    | '/track/$bookingId'
    | '/admin/'
    | '/expert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookingsRoute: typeof BookingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupCustomerRoute: typeof AuthSignupCustomerRoute
  AuthSignupExpertRoute: typeof AuthSignupExpertRoute
  BookServiceIdRoute: typeof BookServiceIdRoute
  InvoiceBookingIdRoute: typeof InvoiceBookingIdRoute
  PSlugRoute: typeof PSlugRoute
  TrackBookingIdRoute: typeof TrackBookingIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/': {
      id: '/expert/'
      path: '/expert'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$bookingId': {
      id: '/track/$bookingId'
      path: '/track/$bookingId'
      fullPath: '/track/$bookingId'
      preLoaderRoute: typeof TrackBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$bookingId': {
      id: '/invoice/$bookingId'
      path: '/invoice/$bookingId'
      fullPath: '/invoice/$bookingId'
      preLoaderRoute: typeof InvoiceBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$serviceId': {
      id: '/book/$serviceId'
      path: '/book/$serviceId'
      fullPath: '/book/$serviceId'
      preLoaderRoute: typeof BookServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup-expert': {
      id: '/auth/signup-expert'
      path: '/auth/signup-expert'
      fullPath: '/auth/signup-expert'
      preLoaderRoute: typeof AuthSignupExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup-customer': {
      id: '/auth/signup-customer'
      path: '/auth/signup-customer'
      fullPath: '/auth/signup-customer'
      preLoaderRoute: typeof AuthSignupCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookingsRoute: BookingsRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupCustomerRoute: AuthSignupCustomerRoute,
  AuthSignupExpertRoute: AuthSignupExpertRoute,
  BookServiceIdRoute: BookServiceIdRoute,
  InvoiceBookingIdRoute: InvoiceBookingIdRoute,
  PSlugRoute: PSlugRoute,
  TrackBookingIdRoute: TrackBookingIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ExpertIndexRoute: ExpertIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
